### ISSUE TITLE
Cannot add Pages to Book of the Legends

### ISSUE THREAD

**Issue by BioMasterZap** [Faxundo/OldLegends#1]
Hello, I've been testing out Old Legends v4.0.0 for Fabric 1.20.4 and I cannot seem to get any pages to add to the Book of Legends. I have shift right click to bind the book to me, but when I open it, it only shows the 4 ??? spaces that always seem to close out of the book interface when clicked. I tried right clicking and shift right clicking the book with pages in my inventory or offhand but it only opens the book. I also tried right clicking and shift right clicking the pages, crafting table, cartography table, and anvil with no luck.

I am not sure if there is a bug or if I am just not figuring out the intended way to add pages, but I did look around at the code and it seemed like it was supposed to be a shift right click with the book or something similar to add pages. If there is another method I am missing, let me know.

**Comment by Faxundo** [comment]
Hi. Yes, only there 4 slot, each one is for a old legends item. It's normal what gui close when you click in there, beacuse the misions and another gui what should be there, still not implemented.
For add pages to the book, it's works like a vanilla bundle. In the inventory left click in the book and later right click in the page. Then a message what page is added shows in the chat. 
Runes pages don't appear in the gui but pages of old legends item should be.

**Comment by BioMasterZap** [comment]
Ah, that did it. Guess I was too used to bundle tweak mods and only tried clicking the page on the book, not the book on the page. Might be nice if both interactions worked, but might not be as easy to do the other way around. The mod ingame probably should try to be a bit more clear on how to add the pages though since bundle mechanics aren't very common or expected for a book. Maybe somewhere in the open book it can try to mention or show it.


Also, couple notes now that I got the pages in the book. First is that it could use some sort of tooltip to tell you how many pages were added or some section in the interface to list which pages were added. The advanced tooltips does show the NBT, but if you don't use advanced tooltips it is kinda unclear.

Second, now that I got the pages I've been trying out the rune table. I can get the Death Rune and Time Runes to craft, but I seem unable to put the lapis in the slots marked with the gem icon to make the shape for the sky rune. Also, instant crafting is a bit jarring and can cause some issues. When I was filling out the pattern for Time Rune, it filled the slots needed for Death Rune and instantly crafted it; it does this even if there is a Lapis in additional slots, so the only way to avoid it is to fill the top right or bottom left slot last.

**Comment by Faxundo** [comment]
Yes, i totally agree. Few features what i implemented not are so clear as they should be.

I not sure about the tooltip for number of pages. I thought what "?" into the book is enough. Mmm maybe don't be a problem add that feature. I guess there is never enough clarity. 

I still working in the rune table. I didn't know how use the encode of fabric, so i created the recipes manually. I would like what rune table works like a workbench. That is the objective and add some feature with the pilar of amethyst besides unlock slots. Ah, you need boost with Amethyst Pillars the table for craft a Sky Rune. The amethyst symbol of slots indicate what slot unlock with the pillar.

![Sin título](https://github.com/user-attachments/assets/b78faa4a-ee4b-4ef4-95b1-9db4932d40ad)

**Comment by Faxundo** [comment]
Your suggestion has been added in the 5.0.0 version and the rune table should be work better now.
